#!/bin/bash -e
# Copyright 2017-2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Hosting https://sdrausty.github.io/TermuxArch courtesy https://pages.github.com
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.  
# https://sdrausty.github.io/TermuxArch/README has information about this project. 
# https://www.bing.com/search?q=grey+music+cognition
################################################################################
while true;do printplay "$@";play-audio "$@" 1>/dev/null; (( snooze="$(sed 's/[^0-9]//g' /proc/sys/kernel/random/uuid |sed 's/^\(...\).*/\1/')" )) ;printsnooze "$@";sleep "$snooze";done
