#!/bin/bash
# Copyright 2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Website for this project at https://sdrausty.github.io/TermuxArch
# See https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank You! 
# From http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_03.html
# Regarding https://github.com/sdrausty/TermuxArch/issues/37
# This script does a very simple test for checking disk space.

space=`df /storage/emulated/0 | awk '{print $4}' | sed '2q;d'`
echo $space
printf $space
if [[ $space == *G ]];then
  Message="All is quiet."
else
	Message="Start thinking about cleaning out some stuff.  There's a partition that is ($space) % full."
	Message="Start thinking about cleaning out some stuff.  There's a partition that is $space % full."
	Message="Start thinking about cleaning out some stuff.  There's a partition that is % full."
fi

printf "\nBegin Case\n"
case $space in
*[G]*)
  cMessage="All is quiet."
  ;;
*[M]*)
  cMessage="Start thinking about cleaning out some stuff.  There's a partition that is $space % full."
  ;;
9[1-8])
  cMessage="Better hurry with that new disk...  One partition is $space % full."
  ;;
99)
  cMessage="I'm drowning here!  There's a partition at $space %!"
  ;;
*)
  cMessage="I seem to be running with an nonexistent amount of disk space..."
  ;;
esac
printf "\nEnd Case\n"

printf "\nCase Message\n"
printf=\n$cMessage\n 
printf "\nIf Message\n"
printf "\n$Message\n"
printf "\nDate Message\n"
printf "\ndisk report `date`\n"
printf "\nIf Message\n"
printf "\n$Message\n"
