#!/bin/bash -e
# Copyright 2017-2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Hosting https://sdrausty.github.io/TermuxArch courtesy https://pages.github.com
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.  
# https://sdrausty.github.io/TermuxArch/README has information about this project. 
################################################################ ###############
DATA[0]="   ___           __     __   _                  _       "
DATA[1]="  / _ | ________/ /    / /  (_)__  __ ____ __  (_)__    "
DATA[2]=" / __ |/ __/ __/ _ \  / /__/ / _ \/ // /\ \ / / / _ \   "
DATA[3]="/_/ |_/_/  \__/_//_/ /____/_/_//_/\_,_//_\_\ /_/_//_/   "
DATA[4]="                                                        "
DATA[5]=" ______                          ___  ___            __ "
DATA[6]="/_  __/__ ______ _  __ ____ __  / _ \/ _ \___  ___  / / "
DATA[7]=" / / / -_) __/  ' \/ // /\ \ / / ___/ , _/ _ \/ _ \/ __/"
DATA[8]="/_/  \__/_/ /_/_/_/\_,_//_\_\ /_/  /_/|_|\___/\___/\__/ "

# virtual coordinate system is X*Y ${#DATA} * 5

REAL_OFFSET_X=0
REAL_OFFSET_Y=0

draw_char() {
  V_COORD_X=$1
  V_COORD_Y=$2

  tput cup $((REAL_OFFSET_Y + V_COORD_Y)) $((REAL_OFFSET_X + V_COORD_X))

  printf %c ${DATA[V_COORD_Y]:V_COORD_X:1}
}


trap 'exit 1' INT TERM
trap 'tput setaf 9; tput cvvis; clear' EXIT

tput civis
clear

while :; do

for ((c=1; c <= 7; c++)); do
  tput setaf $c
  for ((x=0; x<${#DATA[0]}; x++)); do
    for ((y=0; y<=9; y++)); do
      draw_char $x $y
    done
  done
done

done
