#!/bin/bash
# Copyright 2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Website for this project at https://sdrausty.github.io/TermuxArch
# See https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank You! 
# Based on http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_03.html
# Regarding https://github.com/sdrausty/TermuxArch/issues/37
# This script does a very simple test for checking disk space.

space=`df /storage/emulated/0 | awk '{print $4}' | sed '2q;d'`
printf $space
if [[ $space = *G ]] || [[ $space = *T ]];then
#if [ $space == *G ];then
	Message="All is quiet."
else
	Message="Start thinking about cleaning out some stuff.  There's a partition that has just $space."
fi

printf "\n$Message\n"
printf "\nDate Message\n"
printf "\nDisk report $space on `date`\n"
